

TILE_SIZE = 32
GRID_WIDTH = 30 
GRID_HEIGHT = 20
SCREEN_WIDTH = GRID_WIDTH * TILE_SIZE
SCREEN_HEIGHT = GRID_HEIGHT * TILE_SIZE
AGENT_SCALE = 2

PANEL_WIDTH = 36
PANEL_HEIGHT = 16
PANEL_COLOR = (255, 255, 255)

ASSETS_ROOT_PATH = "./examples/office/data/"

FPS = 60